####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: lazy.symfony

###########
# Project #
###########

project:
    name: elao

##########
# System #
##########

system:
    nginx:
        version: 1.24
        port: 35080
    php:
        version: 8.3
        extensions:
          - gd
    nodejs:
        version: 22
    network:
        ports:
          - 8080:8080 # Webpack dev server
