services:

    ##########
    # System #
    ##########

    system:
        volumes:
            - ${MANALA_DOCKER_SOCK}:${MANALA_DOCKER_SOCK_BIND:-${MANALA_DOCKER_SOCK}}
        environment:
            MANALA_DOCKER_SOCK: ${MANALA_DOCKER_SOCK}
            MANALA_DOCKER_SOCK_BIND: ${MANALA_DOCKER_SOCK_BIND:-}
