services:

    ##########
    # System #
    ##########

    system:
        build:
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        environment:
            # Php - XDebug
            PHP_XDEBUG_DISCOVER_CLIENT_HOST: 1
